#@TYPE: Machine
#@NAME: Titan-8
#@DESCRIPTION: Machine configuration for the ADI Titan-8 (ADRV906X) SoC

require conf/machine/include/adrv906x_common.inc
require conf/machine/include/adrv906x_dual.inc
require conf/machine/include/adi_default_settings.inc

TFA_HW_CONFIG = "denali_8"
TFA_FW_CONFIG = "denali_8-fw-config"

MACHINEOVERRIDES:prepend = "titan:"
